### ISSUE TITLE
Cloud Build is failed with missing promotionenginesamplesaddon/project.properties.template

### ISSUE THREAD

**Issue by year1997** [SAP-samples/cloud-commerce-sample-setup#22]
In SAP Commerce Cloud, simply trigger a new build on branch 2105-spartacus. 

The build is failed with this error:
`     [echo] Generate project.properties file from template /opt/workspace/build/commerce-suite/hybris/bin/modules/promotion-engine/promotionenginesamplesaddon/project.properties.template

BUILD FAILED
/opt/workspace/build/commerce-suite/hybris/bin/modules/core-accelerator/addonsupport/resources/addonsupport/ant/acc-ant-addons.xml:730: The following error occurred while executing this line:
/opt/workspace/build/commerce-suite/hybris/bin/modules/core-accelerator/addonsupport/resources/addonsupport/ant/acc-ant-addons.xml:644: The following error occurred while executing this line:
/opt/workspace/build/commerce-suite/hybris/bin/modules/core-accelerator/addonsupport/resources/addonsupport/ant/acc-ant-addons.xml:648: The following error occurred while executing this line:
/opt/workspace/build/commerce-suite/hybris/bin/modules/core-accelerator/addonsupport/resources/addonsupport/ant/acc-ant-addons.xml:321: project.properties.template file doesn't exist : /opt/workspace/build/commerce-suite/hybris/bin/modules/promotion-engine/promotionenginesamplesaddon/project.properties.template

Total time: 3 seconds
Overall progress: 35
2021-09-20T02:32:44.216Z Task task ':buildCoreCommerce' finished

> Task :buildCoreCommerce FAILED
:buildCoreCommerce (Thread[Daemon worker,5,main]) completed. Took 9.58 secs.

FAILURE: Build failed with an exception.
`

**Comment by mpern** [comment]
Thank you for reporting this, I will fix it today.

**Comment by year1997** [comment]
Thank you @mpern .

I tried with the latest code and build success now.
