### ISSUE TITLE
manifest.json property "tomcat.maxthreads" is missleading

### ISSUE THREAD

**Issue by Ryukki** [SAP-samples/cloud-commerce-sample-setup#24]
This property does not work in CCv2, as the server.xml is generated from different inputs.

It seems to be used in spartacus branches, e.g:
https://github.com/SAP-samples/cloud-commerce-sample-setup/blob/2105-spartacus/core-customize/manifest.json#L198

**Comment by mpern** [comment]
Thank you for reporting this!

Let me double-check how exactly the property is used (or not) and update the template accordingly.

**Comment by mpern** [comment]
changed to the correct property
