### ISSUE TITLE
Create a JSON Schema to Validate "manifest.json"

### ISSUE THREAD

**Issue by adamreisberg** [SAP-samples/cloud-commerce-sample-setup#8]
In addition to utilizing SAP Help portal for documentation of the `manifest.json` file used for deployments, create a publicly-accessible [JSON Schema](https://json-schema.org/understanding-json-schema/index.html) to reduce errors in the creation of builds for SAP Commerce.

## What a `manifest.json` JSON Schema support in SAP Commerce/Cloud Portal Looks Like
1. Freely accessible
1. Abides by [JSON Schema](https://json-schema.org/)
1. Support in the `manifest.json` to reference the schema
   ```json
   {
    "$schema": "http://example.com/sap-commerce-cloud-schema",
    "commerceSuiteVersion": "1905",
    "extensions": [
        "modeltacceleratorservices"
    ],
    ```
## Why a JSON Schema for `manifest.json`?
1. Reduces build errors from incorrectly formatted `manifest.json`
1. Understand value "defaults"
1. Autocomplete/Correction available where JSON Schema is supported ([VSCode](https://code.visualstudio.com/docs/languages/json#_json-schemas-and-settings))

**Comment by mpern** [comment]
Since I had similar issues, I've added manifest.json validation to my Commerce Gradle plugin (now part of the SAP open source offering)

https://github.com/SAP/commerce-gradle-plugin/

**Comment by adamreisberg** [comment]
@mpern thanks for the feedback. Per your feedback, I'll close this issue.
